### ISSUE TITLE
猫神更新了push函数，增加了arguement，之前是三个，现在是四个，onebyone需要新增参数

### ISSUE THREAD

**Issue by LeanFly** [xumf/onebyone#1]
猫神更新了push函数，增加了arguement，之前是三个，现在是四个，onebyone需要新增参数
_

> develop/onebyone/init.go:31:11: not enough arguments in call to push
>         have (string, string, nil)
>         want (interface {}, string, interface {}, string)

_

**Comment by xumf** [comment]
已解决
